#!/usr/bin/env sh

git diff --name-status master | grep 'docs/' 1>/dev/null
DOCS_FOLDER_HAS_CHANGED=$?

# We don't run the docs linting if no changes were made in the docs
if [ "$DOCS_FOLDER_HAS_CHANGED" = "1" ]; then
  exit 0
fi

yarn run lint:js && \
yarn run lint:css && \
yarn run lint:md
