blank_issues_enabled: false

contact_links:
  - name: Documentation feedback
    url: https://github.com/algolia/docsearch/issues/new
    about: Share with us issues about the DocSearch documentation.

  - name: Apply for DocSearch
    url: https://docsearch.algolia.com/apply
    about: Apply to integrate DocSearch to your website.
