#!/usr/bin/env bash
# This will attempt to automatically fix most of the Markdown linting issues
# detected.
set -e

# Lint only file specified through FILES_TO_LINT (done in the pre-commit hook)
# or fallback to all markdown files
FILES_TO_LINT=($FILES_TO_LINT)
if [ "${#FILES_TO_LINT[@]}" = "0" ]; then
  FILES_TO_LINT=(./*.md ./src/*.md)
fi

# We will first transform the file according to remark config. This will mostly
# convert inline links to references at the bottom of the file.
REMARK_MODE=fix \
  remark \
    --quiet \
    "${FILES_TO_LINT[@]}" \
    --output

# We then check the actual natural language content of the file, to fix
# misspellings, punctuation and other fixable issues.
TEXTLINT_MODE=fix textlint \
  --fix \
  --cache \
  "${FILES_TO_LINT[@]}" \
  1>/dev/null

# Finally, we'll run everything through prettier to make sure all files are
# formatted the same way. This will remove trailing spaces, fit all content
# under 80 char long lines, etc
prettier \
  --loglevel error \
  --write \
  "${FILES_TO_LINT[@]}"
