#!/usr/bin/env sh

# Check text content (misspelling, weasel words, offensive writing)
textlint ./*.md ./src/*.md

# Check markdown styling (links, spacing, etc)
remark \
  --no-stdout \
  --quiet \
  --frail \
  ./src/*.md

