#!/usr/bin/env bash
# We first check if, among the files ready to be committed, we have some
# documentation markdown files.
CHANGED_MARKDOWN_FILES="$(git diff --cached --name-only HEAD | grep '^docs/\(.*\).md$')"
if [ "$CHANGED_MARKDOWN_FILES" = "" ]; then
  echo "No markdown file changed"
  exit 0
fi

# We now run the auto-fix linting on only those files
cd ./docs || exit 1
echo "Running auto-lint..."
# Converting the list into a list relative to the ./docs folder, all on one line
RELATIVE_CHANGED_MARKDOWN_FILES="$(
  echo "$CHANGED_MARKDOWN_FILES" \
    | sed 's/^docs/./g' \
    | tr '\n' ' '
)"
FILES_TO_LINT="$RELATIVE_CHANGED_MARKDOWN_FILES" yarn run lint:md:fix

# We re-add those changed files to the index so they show up in the commit
cd ..
FILES_TO_ADD=($CHANGED_MARKDOWN_FILES)
git add "${FILES_TO_ADD[@]}"
