#!/usr/bin/env bash
# This script will warn about changes made to the documentation website when
# submitting a PR to it
#
# Stop if not running inside Travis
# Stop if not in a PR
# Stop if no changes made to the ./docs
# Succeed if no difference in ./dist
# Display diff if differences
exit 0

