[Settings]

[build]
[build.environment]
  NODE_ENV = "development"
  YARN_VERSION = "1.9.4"

# Deploy previews on each PR
[context.deploy-preview]
  command = "./scripts/netlify/deploy-preview"
  publish = "docs/dist"
