#!/usr/bin/env bash

set -e # exit when error

VERSION=$(json version < package.json)
NAME='docsearch.js'
LICENSE="/*! ${NAME} ${VERSION:-UNRELEASED} | © Algolia | github.com/algolia/docsearch.js */"
DIST_DIR="dist/cdn"
DIST_FILE="$DIST_DIR/${NAME}.css"
DIST_FILE_MIN="$DIST_DIR/${NAME}.min.css"

mkdir -p "$DIST_DIR"

# ./dist/cdn/docsearch.css
echo "$LICENSE" > "$DIST_FILE";
node-sass --output-style expanded ./src/styles/main.scss \
  | postcss --use autoprefixer \
  >> "$DIST_FILE"

# ./dist/cdn/docsearch.min.css
postcss --use cssnano "$DIST_FILE" \
  >> "$DIST_FILE_MIN"

gzip_size=$(gzip -9 < $DIST_FILE_MIN | wc -c | pretty-bytes)
echo "=> $DIST_FILE_MIN gzipped will weight $gzip_size-bytes"
