#!/usr/bin/env bash
# This will be called on every commit to the repo and will trigger the
# appropriate ./precommit script for the root project and the ./docs subfolder
# based on which file were changed
HAS_CHANGES_IN_ROOT="0"
HAS_CHANGES_IN_DOCS="0"
HAS_SCRIPT_IN_ROOT="0"
HAS_SCRIPT_IN_DOCS="0"

# Did we change files in root or docs?
CHANGED_FILES="$(git diff --cached --name-only HEAD)"
if echo "$CHANGED_FILES" | grep -qv '^docs/'; then
  HAS_CHANGES_IN_ROOT="1"
fi
if echo "$CHANGED_FILES" | grep -q '^docs/'; then
  HAS_CHANGES_IN_DOCS="1"
fi

# Do we have a precommit script in root or docs?
if [ -x ./scripts/precommit ]; then
  HAS_SCRIPT_IN_ROOT="1"
fi
if [ -x ./docs/scripts/precommit ]; then
  HAS_SCRIPT_IN_DOCS="1"
fi

# Execute the needed scripts
if [ $HAS_CHANGES_IN_ROOT = "1" ] && [ $HAS_SCRIPT_IN_ROOT = "1" ]; then
  echo "Running precommit in ./"
  ./scripts/precommit || exit 1
fi
if [ $HAS_CHANGES_IN_DOCS = "1" ] && [ $HAS_SCRIPT_IN_DOCS = "1" ]; then
  echo "Running precommit in ./docs"
  ./docs/scripts/precommit || exit 1
fi


