#!/usr/bin/env bash

yarn run build:css

echo "Find all files at http://127.0.0.1:8080/";
parallelshell \
  'webpack --config webpack.serve.config.babel.js -w' \
  'onchange "./src/styles/*.scss" -- yarn run build:css' \
  'live-server --no-browser ./dist/cdn' \
  "${BROWSER} scripts/playground.html"

