#!/usr/bin/env bash

set -ev # exit when error

npm run test
NODE_ENV=production npm run build

if [ "$TRAVIS_PULL_REQUEST" == 'false' ] && [ "$TRAVIS_BRANCH" == 'master' ]; then
  ./scripts/finish-release
fi
