# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

gem 'rake'

# Middleman Gems
gem 'middleman', '>= 4.0.0'
gem 'middleman-livereload'
gem 'middleman-syntax'
gem 'middleman-autoprefixer'
gem 'middleman-s3_sync', github: 'fredjean/middleman-s3_sync', ref: '8c4e57a'
gem 'middleman-minify-html'
gem 'sprockets', '4.0.0.beta4'
gem 'middleman-sprockets'
gem 'sprockets-es6'
gem 'redcarpet', '>= 3.3.4'
gem 'nokogiri'
gem 'sassc'
gem 'kramdown', '>= 1.12.0'
gem 'pry-byebug'
gem 'rb-readline'
gem 'mime-types'
gem 'highlight', :require => 'simplabs/highlight' # TODO: Replace with rouge
gem 'htmlentities'
gem 'better_errors'
gem 'binding_of_caller'
gem 'octokit'
gem 'google-api-client', '0.8.6'
gem 'algoliasearch'
gem 'middleman-vcs-time'
gem 'hashie', '3.4.6'
gem 'haml', '4.0.7'
