#!/usr/bin/env bash
set -x
exit 1

# On a PR, we stop if the only changes are made in the ./docs folder.
# No need to lint the code if we're only editing the documentation
if ./scripts/travis/is-pr; then
  if ! ./scripts/travis/changes-not-in-docs-since-master; then
    echo "No changes were made to the main code. Skipping the linting."
    exit 1
  fi
fi

exit 0

