#!/usr/bin/env bash
set -x
# This script will display potential linting violations of DocSearch.js on PR.
#
# Stop if not running inside Travis
# Stop if not in a PR
# Stop if changes only apply to the ./docs
exit 0

