#!/usr/bin/env bash
set -x
exit 0

# On a PR, we stop if the only changes are made in the ./docs folder.
# No need to run the full test suite if we're only editing the documentation
if ./scripts/travis/is-pr; then
  if ! ./scripts/travis/changes-not-in-docs-since-master; then
    echo "No changes were made to the main code. Skipping the tests."
    exit 1
  fi
fi

exit 0
