#!/usr/bin/env bash
set -x
# This script will warn about failing tests in PR and will also be used to
# display the GitHub badge.

# On a PR, we succeed quickly if the only changes are made in the ./docs folder.
# No need to run the full test suite if we're only editing the documentation
if ./scripts/travis/is-pr; then
  if ! ./scripts/travis/changes-not-in-docs-since-master; then
    echo "No changes were made to the main code. Skipping the tests."
    exit 0
  fi
fi

yarn run test || exit 1
