name: 🚀 Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - 'v*'
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: true

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  select-mode:
    runs-on: ubuntu-latest
    outputs:
      mode: ${{ steps.select-mode.outputs.mode }}
      publish-plan-artifact-id: ${{ steps.select-mode.outputs.publish-plan-artifact-id }}
    permissions:
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Set up Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6
        with:
          bun-version-file: .tool-versions

      - name: Install dependencies
        run: bun install

      - name: Select Changesets mode
        id: select-mode
        uses: changesets/action/select-mode@2d9f7af6402422be60d377f151c7618011bba45a

  version:
    # if: needs.select-mode.outputs.mode == 'version'
    # needs: select-mode
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.version.outputs.version.pr-number }}
    permissions:
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Set up Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6
        with:
          bun-version-file: .tool-versions

      - name: Install dependencies
        run: bun install

      - name: Version packages
        id: version
        uses: changesets/action/version@2d9f7af6402422be60d377f151c7618011bba45a
        with:
          pr-title: 🚀 Release
          script: bun run version

  pack:
    if: needs.select-mode.outputs.mode == 'publish'
    needs: select-mode
    runs-on: ubuntu-latest
    outputs:
      pack-dir-artifact-id: ${{ steps.pack.outputs.pack-dir-artifact-id }}
    permissions:
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Set up Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6
        with:
          bun-version-file: .tool-versions

      - name: Install dependencies
        run: bun install

      - name: Build packages
        run: bun run build

      - name: Pack packages
        id: pack
        uses: changesets/action/pack@2d9f7af6402422be60d377f151c7618011bba45a
        with:
          publish-plan-artifact-id: ${{ needs.select-mode.outputs.publish-plan-artifact-id }}

  publish:
    needs: pack
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check out repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Set up Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6
        with:
          bun-version-file: .tool-versions

      - name: Install dependencies
        run: bun install

      - name: Publish packages
        uses: changesets/action/publish@2d9f7af6402422be60d377f151c7618011bba45a
        with:
          pack-dir-artifact-id: ${{ needs.pack.outputs.pack-dir-artifact-id }}
          script: bun run release
